### ISSUE TITLE
Why the mPs from TestData_Perturbed_Results.mat are not consistent with that in your paper?

### ISSUE THREAD

**Issue by guohengkai** [twerdster/HandNet#1]
Hi,

I have run your code with the threshold 15 and calculated the mean mPs(average the mP from 1 to 5) for forest and CNN with derotcnn. I got the result:

forest: mP 0.6439 mAP 0.8810
CNN:  mP 0.5616 mAP 0.8287

Can you tell me what your evaluation method is? Thanks.

**Comment by twerdster** [comment]
Between the time the paper was published and the code and data was uploaded there was a crash of our computing infrastructure and the data had to be regenerated. As a result there are some discrepancies between the published results and those available in this repo. We intend to submit a request to add an errata document to BMVC at some point in the future with updated results. However, it is important to note that the core properties of the results and their interactions (i.e. that learning and testing on derotated data is better than learning and testing on underotated etc) remains the same. The conclusions of the paper have thus not been affected.

**Comment by guohengkai** [comment]
OK. Thank you for your response.
